exports.fieldToAbbrMap = {
    "Accounting": "ACCTG",
    "Anatomy": "ANATMY",
    "American Sign Language": "ASL",
	"Art": "ART",
    "Astronomy": "ASTRON",
    "Biology": "BIOL",
    "Microbiology": "MCRBIO",
    "Business": "BUS",
    "Chemistry": "CHEM",
    "Chinese": "CHNESE",
    "Computer Applications": "CIS",
    "Computer Science": "CS",
    "Cosmetology": "COSM",
    "Counseling": "COUNS",
    "Dance": "DANCE",
    "Early Childhood Education": "ECE",
    "Economics": "ECON",
    "Engineering": "ENGR",
    "English": "ENGL",
    "Entertainment Technology": "ET",
    "English for Second Language": "ESL",
    "Fashion": "FASHN",
    "Film Studies": "FILM STUDIES",
    "French": "FRENCH",
    "Geographic Information Systems": "GIS",
    "Geography": "GEOG",
    "German": "GERMAN",
    "Graphic Design": "GR DES",
    "Hebrew": "HEBREW",
    "History": "HIST",
    "Humanities": "HUM",
    "Interior Architectural Design": "INTARC",
    "Italian": "ITAL",
    "Japanese": "JAPAN",
    "Journalism": "JOURN",
    "Kinesiology Physical Education": "KIN PE",
    "Korean": "KOREAN",
    "Math": "MATH",
    "Media Studies": "MEDIA",
    "Music": "MUSIC",
    "Nursing": "NURSNG",
    "Office Technology": "OFTECH",
    "Photography": "PHOTO",
    "Photovoltaic Systems": "PV",
    "Physics": "PHYSCS",
    "Political Science": "POL SC",
    "Psychology": "PSYCH",
    "Physiology": "PHYS",
    "Religious Studies": "REL ST",
    "Respiratory Therapy": "RES TH",
    "Spanish": "SPAN",
    "Theater Arts": "TH ART",
    "Women's Studies": "WOM ST"
};

exports.abbrToFieldMap = {
    "ACCTG": "Accounting",
    "ANATMY": "Anatomy",
    "ASL": "American Sign Language",
	"ART": "Art",
    "ASTRON": "Astronomy",
    "BIOL": "Biology",
    "MCRBIO": "Microbiology",
    "BUS": "Business",
    "CHEM": "Chemistry",
    "CHNESE": "Chinese",
    "CIS": "Computer Applications",
    "CS": "Computer Science",
    "COSM": "Cosmetology",
    "COUNS": "Counseling",
    "DANCE": "Dance",
    "ECE": "Early Childhood Education",
    "ECON": "Economics",
    "ENGR": "Engineering",
    "ENGL": "English",
    "ET": "Entertainment Technology",
    "ESL": "English for Second Language",
    "FASHN": "Fashion",
    "FILM STUDIES": "Film Studies",
    "FRENCH": "French",
    "GIS": "Geographic Information Systems",
    "GEOG": "Geography",
    "GERMAN": "German",
    "GR DES": "Graphic Design",
    "HEBREW": "Hebrew",
    "HIST": "History",
    "HUM": "Humanities",
    "INTARC": "Interior Architectural Design",
    "ITAL": "Italian",
    "JAPAN": "Japanese",
    "JOURN": "Journalism",
    "KIN PE": "Kinesiology Physical Education",
    "KOREAN": "Korean",
    "MATH": "Math",
    "MEDIA": "Media Studies",
    "MUSIC": "Music",
    "NURSNG": "Nursing",
    "OFTECH": "Office Technology",
    "PHOTO": "Photography",
    "PV": "Photovoltaic Systems",
    "PHYSCS": "Physics",
    "POL SC": "Political Science",
    "PSYCH": "Psychology",
    "PHYS": "Physiology",
    "REL ST": "Religious Studies",
    "RES TH": "Respiratory Therapy",
    "SPAN": "Spanish",
    "TH ART": "Theater Arts",
    "WOM ST": "Women's Studies"
};




exports.fields_abbrv = [
    "ACCTG",
    "ANATMY",
    "ASL",
	"ART",
    "ASTRON",
    "BIOL",
    "MCRBIO",
    "BUS",
    "CHEM",
    "CHNESE",
    "CIS",
    "CS",
    "COSM",
    "COUNS",
    "DANCE",
    "ECE",
    "ECON",
    "ENGR",
    "ENGL",
    "ET",
    "ESL",
    "FASHN",
    "FILM STUDIES",
    "FRENCH",
    "GIS",
    "GEOG",
    "GERMAN",
    "GR DES",
    "HEBREW",
    "HIST",
    "HUM",
    "INTARC",
    "ITAL",
    "JAPAN",
    "JOURN",
    "KIN PE",
    "KOREAN",
    "MATH",
    "MEDIA",
    "MUSIC",
    "NURSNG",
    "OFTECH",
    "PHOTO",
    "PV",
    "PHYSCS",
    "POL SC",
    "PSYCH",
    "PHYS",
    "REL ST",
    "RES TH",
    "SPAN",
    "TH ART",
    "WOM ST"
];





exports.fields = ["Accounting",
"Anatomy",
"American Sign Language",
"Art",
"Astronomy",
"Biology",
"Microbiology",
"Business",
"Chemistry",
"Chinese",
"Computer Applications",
"Computer Science",
"Cosmetology",
"Counseling",
"Dance",
"Early Childhood Education",
"Economics",
"Engineering",
"English",
"Entertainment Technology",
"English for Second Language",
"Fashion",
"Film Studies",
"French",
"Geographic Information Systems",
"Geography",
"German",
"Graphic Design",
"Hebrew",
"History",
"Humanities",
"Interior Architectural Design",
"Italian",
"Japanese",
"Journalism",
"Kinesiology Physical Education",
"Korean",
"Math",
"Media Studies",
"Music",
"Nursing",
"Office Technology",
"Photography",
"Photovoltaic Systems",
"Physics",
"Political Science",
"Psychology",
"Physiology",
"Religious Studies",
"Respiratory Therapy",
"Spanish",
"Theater Arts",
"Women's Studies"];
